### PR TITLE
Gem updates required to run app

### PR DESCRIPTION
**Pull request by ewalk153**
- Mimemagic version in Gemfile.lock was revoke due to license changes
- Puma version failed to compile
- Minitest and listen had build failures

Ran `bundle update mimemagic minitest listen puma` to generate this change.

### CODE REVIEW

**Comment by eoinkelly** [comment]
I had to change this to `bundle update mimemagic minitest listen puma nokogiri` (adding `nokogiri`).

**Comment by santiagorodriguez96** [comment]
Are you still having issues to build the app? I noticed the build was failing in Travis CI because of `mimemagic` and I solved it by updating Rails to `v6.0.6` – see #122. Now the build seems to be working properly 🙂

**Comment by heliocola** [comment]
Hi @santiagorodriguez96 : there is another PR with upgrade to Ruby 3.1.4 as 2.7.7 is quite old and past EOL (https://endoflife.date/ruby).

Any chance you can spend some time to upgrade?
I am setting it up on my machine as I will talk about it at Ruby Conf Taiwan next month! :-D

**Comment by heliocola** [comment]
👋 @ewalk153 : thank you for sending this PR!

Did you have a chance to check out the latest changes in the master branch?
Several gems, ruby, rails all have been updated.

@santiagorodriguez96 : I think the issues on this one are taken care in the other PRs, specially in the Rails 7 upgrade! 👍

**Comment by santiagorodriguez96** [comment]
Hey guys! I've bumped pretty much all of the dependencies, so there shouldn't be an issue now. Will proceed to close this 🙂

**Pull request closed without merging**
